env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project":
    - './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules: {
  'indent': ['error', 2],
  'object-curly-spacing': ['error', 'always'],
  'array-bracket-spacing': ['error', 'always']
}
ignorePatterns:
  - '*/node_modules/*'
  - '*.scss'
  - '*.js'
  - '*.d.ts'
  - '*genql*'
