export enum ErrorCodes {
	GET_USER_FAILED = 'GET_USER_FAILED',
	PUT_USER_FAILED = 'PUT_USER_FAILED',
	UPDATE_USER_FAILED = 'UPDATE_USER_FAILED',
	DELETE_USER_FAILED = 'DELETE_USER_FAILED',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
}

export default ErrorCodes;
