name: Node.js CI

on:
    push:
        branches:
            - "**"
        tags-ignore:
            - "**"
    pull_request:
        branches: [main, develop]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x, 15.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: cd  solution/server
            - run: yarn --frozen-lockfile
            - run: yarn build
            - run: yarn test
